---
pull_request_rules:
  -
    actions:
      merge:
        method: squash
    conditions:
      - author!=Clivern
      - approved-reviews-by=Clivern
      - label=merge
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    name: "Automatic Merge 🚀"
  -
    actions:
      merge:
        method: merge
    conditions:
      - author=Clivern
      - label=merge
    name: "Automatic Merge 🚀"
  -
    actions:
      merge:
        method: squash
    conditions:
      - "author=renovate[bot]"
      - label=merge
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    name: "Automatic Merge for Renovate PRs 🚀"
  -
    actions:
      comment:
        message: "Nice! PR successfully merged."
    conditions:
      - merged
    name: "Merge Done 🚀"
