---
pull_request_rules:
  -
    actions:
      merge:
        method: squash
    conditions:
      - author!=Clivern
      - approved-reviews-by=Clivern
      - label=release
    name: "Automatic Merge 🚀"
  -
    actions:
      merge:
        method: merge
    conditions:
      - author=Clivern
      - label=release
    name: "Automatic Merge 🚀"
  -
    actions:
      merge:
        method: squash
    conditions:
      - "author=renovate[bot]"
      - label=release
    name: "Automatic Merge for Renovate PRs 🚀"
  -
    actions:
      comment:
        message: "Nice! PR merged successfully."
    conditions:
      - merged
    name: "Merge Done 🚀"
