version: '3'
services:
   redis:
      image: 'redis:5.0.12-alpine'
      volumes:
         - 'redis_data:/data'
      # Allow connection from docker host machine
      # ports:
      #   - "6379:6379"
      restart: always
   web:
      image: "clivern_beaver:1.2.3"
      build: .
      command: './beaver -config=/go/configs/beaver/config.dist.yml'
      ports:
         - "8080:8080"
      depends_on:
         - redis
      volumes:
         - './logs:/go/logs/beaver'
         - './configs:/go/configs/beaver'
      restart: always
      healthcheck:
         test: './beaver -config=/go/configs/beaver/config.dist.yml -exec=health'
         interval: 5s
         timeout: 2s
         retries: 5
volumes:
    redis_data: null