version: '3'
services:
   redis:
      image: 'redis:3.2-alpine'
      volumes:
         - 'redis_data:/data'
      restart: always
   web:
      image: "clivern_beaver:1.0.0"
      build: .
      command: './beaver'
      ports:
         - "8080:8080"
      depends_on:
         - redis
      volumes:
         - './var:/go/src/github.com/clivern/beaver/var'
      restart: always
      environment:
         - AppMode=prod
         - AppPort=8080
         - AppLogLevel=info
         - AppDomain=example.com
         - LogPath=var/logs
         - RedisAddr=redis:6379
         - RedisPassword=
         - RedisDB=0
         - APIToken=123

      restart: always
      healthcheck:
         test: './beaver -exec=health'
         interval: 5s
         timeout: 2s
         retries: 5